
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
Prisma.prismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.EngagementScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  title: 'title',
  description: 'description',
  durationStartDate: 'durationStartDate',
  durationEndDate: 'durationEndDate',
  durationWeeks: 'durationWeeks',
  durationMonths: 'durationMonths',
  timeZones: 'timeZones',
  countries: 'countries',
  requiredSkills: 'requiredSkills',
  anticipatedStart: 'anticipatedStart',
  status: 'status',
  isPrivate: 'isPrivate',
  requiredMemberCount: 'requiredMemberCount',
  role: 'role',
  workload: 'workload',
  compensationRange: 'compensationRange',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.EngagementApplicationScalarFieldEnum = {
  id: 'id',
  engagementId: 'engagementId',
  userId: 'userId',
  handle: 'handle',
  email: 'email',
  name: 'name',
  address: 'address',
  mobileNumber: 'mobileNumber',
  coverLetter: 'coverLetter',
  resumeUrl: 'resumeUrl',
  portfolioUrls: 'portfolioUrls',
  yearsOfExperience: 'yearsOfExperience',
  availability: 'availability',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
};

exports.Prisma.EngagementAssignmentScalarFieldEnum = {
  id: 'id',
  engagementId: 'engagementId',
  memberId: 'memberId',
  memberHandle: 'memberHandle',
  status: 'status',
  agreementRate: 'agreementRate',
  otherRemarks: 'otherRemarks',
  terminationReason: 'terminationReason',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EngagementFeedbackScalarFieldEnum = {
  id: 'id',
  engagementAssignmentId: 'engagementAssignmentId',
  feedbackText: 'feedbackText',
  rating: 'rating',
  givenByMemberId: 'givenByMemberId',
  givenByHandle: 'givenByHandle',
  givenByEmail: 'givenByEmail',
  secretToken: 'secretToken',
  secretTokenExpiresAt: 'secretTokenExpiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MemberExperienceScalarFieldEnum = {
  id: 'id',
  engagementAssignmentId: 'engagementAssignmentId',
  experienceText: 'experienceText',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.AnticipatedStart = exports.$Enums.AnticipatedStart = {
  IMMEDIATE: 'IMMEDIATE',
  FEW_DAYS: 'FEW_DAYS',
  FEW_WEEKS: 'FEW_WEEKS'
};

exports.EngagementStatus = exports.$Enums.EngagementStatus = {
  OPEN: 'OPEN',
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  CLOSED: 'CLOSED'
};

exports.Role = exports.$Enums.Role = {
  DESIGNER: 'DESIGNER',
  SOFTWARE_DEVELOPER: 'SOFTWARE_DEVELOPER',
  DATA_SCIENTIST: 'DATA_SCIENTIST',
  DATA_ENGINEER: 'DATA_ENGINEER'
};

exports.Workload = exports.$Enums.Workload = {
  FULL_TIME: 'FULL_TIME',
  FRACTIONAL: 'FRACTIONAL'
};

exports.ApplicationStatus = exports.$Enums.ApplicationStatus = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  SELECTED: 'SELECTED',
  REJECTED: 'REJECTED'
};

exports.AssignmentStatus = exports.$Enums.AssignmentStatus = {
  SELECTED: 'SELECTED',
  OFFER_REJECTED: 'OFFER_REJECTED',
  ASSIGNED: 'ASSIGNED',
  COMPLETED: 'COMPLETED',
  TERMINATED: 'TERMINATED'
};

exports.Prisma.ModelName = {
  Engagement: 'Engagement',
  EngagementApplication: 'EngagementApplication',
  EngagementAssignment: 'EngagementAssignment',
  EngagementFeedback: 'EngagementFeedback',
  MemberExperience: 'MemberExperience'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
